import = ["~/.config/alacritty-colorscheme/themes/gruvbox_dark.yaml"]
[window]
opacity = 0.8

[scrolling]
history = 50000

[font]
size = 11.0

[colors]
transparent_background_colors = true

[font.normal]
family = "HackNerdFont"
style = "Regular"

[font.bold]
family = "HackNerdFont"
style = "Bold"

[font.italic]
family = "HackNerdFont"
style = "Italic"

[font.bold_italic]
style = "Bold Italic"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[colors.normal]
black = "0x1a1b26"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xa9b1d6"

[colors.bright]
black = "0x414868"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xc0caf5"
